import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Program {
    id: string;
    name: string;
    hospital: string;
    city: string;
    state: string;
    stateCode: string;
    specialty: string;
    subspecialty: string;
    eligibility: {
        usmleSteps: string[];
        visaTypes: string[];
        graduationCutoff: string;
        clinicalExperience: string;
        additionalNotes: string;
    };
    fee: string;
    duration: string;
    contact: {
        email: string;
        phone: string;
        website: string;
        coordinatorName: string;
    };
    applicationDeadline: string;
    acceptingApplications: boolean;
    lastVerified: string;
    lor: boolean;
    tags: string[];
    description: string;
}

const programNames: string[] = [
    "Loyola Medicine MacNeal Hospital Program",
    "McLaren Health Care Corporation Program",
    "McLaren Health Care/Flint/MSU Program",
    "Medical University of South Carolina Regional Network (Florence) Program",
    "Meharry Medical College Program",
    "Mercy St Vincent Medical Center/Mercy Health Partners Program",
    "MetroWest Medical Center Program",
    "Mount Sinai Hospital Medical Center of Chicago Program",
    "Nazareth Hospital Program",
    "New York Medical College/Roxborough Memorial Hospital Program",
    "One Brooklyn Health System/Interfaith Medical Center Program",
    "Our Lady of Lourdes Memorial Hospital Inc Program",
    "Piedmont Athens Regional Program",
    "Prime South GME Consortium/Harlingen Medical Center Program",
    "Prime South GME Consortium/Southern Regional Medical Center Program",
    "Prime West Consortium Program",
    "Rutgers Health/Monmouth Medical Center Program",
    "San Joaquin General Hospital Program",
    "South Georgia Medical Center Program",
    "St Agnes HealthCare Program",
    "St John's Episcopal Hospital-South Shore Program",
    "St Vincent Hospital Program",
    "Texas Tech University (Permian Basin) Program",
    "Texas Tech University HSC El Paso/Hospitals of Providence Transmountain Campus Program",
    "Tower Health/Phoenixville Hospital Program",
    "Trinity Health Oakland/Wayne State University Program",
    "University at Buffalo (Catholic Health System-Sisters of Charity) Program",
    "University of Central Florida/HCA Florida Healthcare (Pensacola) Program",
    "University of Maryland Medical Center Midtown Campus Program",
    "Wayne State University School of Medicine Program",
    "Wellstar Health System Spalding Program",
    "Wellstar Health System/Wellstar Cobb Hospital Program",
    "Woodhull Medical and Mental Health Center Program",
    "New York Medical College/St Mary and St Clare Program",
    "Rochester Regional Health/Rochester General Hospital Program",
    "Jacobi Medical Center/North Central Bronx Hospital Program",
    "Lincoln Medical and Mental Health Center Program",
    "St Barnabas Hospital Program",
    "United Health Services Hospitals Program",
    "Hurley Medical Center/Michigan State University Program",
    "Canton Medical Education Foundation/NEOMED Program",
    "UPMC Medical Education/McKeesport Hospital Program",
    "Prime West Consortium/Centinela Hospital Medical Center Program",
    "Robert Packer Hospital/Guthrie Program",
    "Rutgers Health/Trinitas Regional Medical Center Program",
    "Wyckoff Heights Medical Center Program",
    "Corewell Health (Dearborn) Program",
    "Griffin Hospital Program",
    "SSM St Mary's Hospital-St Louis Program",
    "Larkin Community Hospital Program",
    "Chicago Medical School/Rosalind Franklin University of Medicine and Science Program",
    "Marshfield Clinic Program",
    "Connecticut Institute for Communities Health Program",
    "Mass General Brigham/Salem Hospital Program",
    "One Brooklyn Health System/Brookdale University Hospital and Medical Center Program",
    "Hackensack Meridian Health Program",
    "St Joseph's University Medical Center Program",
    "Wright Center for Graduate Medical Education Program A",
    "Nuvance Health Consortium (Danbury Hospital) Program",
    "St Agnes Medical Center (Fresno) Program",
    "Montefiore Medical Center/Albert Einstein College of Medicine (Wakefield Campus) Program",
    "Henry Ford Health/Henry Ford Jackson Hospital Program",
    "Baptist Health - UAMS Program",
    "Detroit Medical Center/Wayne State University (Sinai Grace) Program",
    "Jacobi Medical Center/Albert Einstein College of Medicine Program",
    "South Texas Health System GME Consortium Program",
    "Bridgeport Hospital/Yale University Program",
    "Chicago Medical School/Rosalind Franklin University/Northwestern Medicine McHenry Hospital Program",
    "New York Medical College at St Michael's Medical Center Program",
    "North Alabama Medical Center Program",
    "Prime West Consortium/Desert Valley Hospital Program",
    "Prime West Consortium/West Anaheim Medical Center Program",
    "Bassett Medical Center Program",
    "Hamilton Medical Center Program",
    "McLaren Health Care/Oakland/MSU Program",
    "University of Texas RGV (Knapp) Program",
    "Mobile Infirmary Medical Center Program",
    "St Elizabeth Youngstown Hospital/NEOMED Program",
    "Arkansas College of Osteopathic Medicine/Mercy Program",
    "Nuvance Health Consortium (Norwalk Hospital/Yale University) Program",
    "Cayuga Medical Center Program",
    "University of Maryland Capital Region Health Program",
    "KPC Global Medical Centers Inc Program",
    "University of Alabama Medical Center (Montgomery) Program",
    "Health Education Services/North Knoxville Medical Center Program",
    "Texas Tech University (Amarillo) Program",
    "Brooklyn Hospital Center Program",
    "Maimonides Medical Center Program",
    "Insight Hospital and Medical Center Chicago Program",
    "University of Central Florida/HCA Florida Healthcare (Greater Orlando/Lake Monroe) Program",
    "Nassau University Medical Center Program",
    "New York Medical College (Metropolitan) Program",
    "Prime Midwest GME Consortium Program",
    "Berkshire Medical Center Program",
    "Richmond University Medical Center Program",
    "TidalHealth Program",
    "Carle Foundation Hospital Program",
    "Rochester Regional Health/Unity Internal Medicine Program",
    "Eisenhower Medical Center Program",
    "North East Medical Services Program",
    "Rutgers Health/Jersey City Medical Center Program",
    "AtlantiCare Regional Medical Center Program",
    "St Francis Medical Center Program",
    "University of Central Florida/HCA Florida Healthcare (Gainesville) Program",
    "Saint Peter's University Hospital/Rutgers Robert Wood Johnson Medical School Program",
    "University of Michigan Health - Sparrow/Michigan State University Program",
    "Greater Baltimore Medical Center Program",
    "MedStar Health Georgetown University/Washington Hospital Center Program",
    "MedStar Health Georgetown University (Baltimore) Program",
    "Kern Medical Center Program",
    "Quinnipiac University Frank H Netter MD SOM/St Vincent's Medical Center Program",
    "SUNY Downstate Health Sciences University (Primary Care) Program",
    "Trinity Health Livonia Hospital/Wayne State University Program",
    "Southeast Health Program",
    "Indiana University School of Medicine/Ball Memorial Program",
    "St Luke's Hospital Program",
    "Arkansas College of Osteopathic Medicine Program",
    "Larkin Community Hospital Palm Springs Campus Program",
    "NYC Health & Hospitals/South Brooklyn Health Program",
    "Mercy Catholic Medical Center Program",
    "Flushing Hospital Medical Center Program",
    "Piedmont Macon Medical Center Program",
    "Cleveland Clinic Foundation/Fairview Hospital Program",
    "St Elizabeth's Medical Center Program",
    "Willis-Knighton Health System Program",
    "Nuvance Health Consortium (Vassar Brothers Medical Center) Program",
    "Rutgers Health/Community Medical Center Program",
    "AdventHealth Florida (Orlando) Program",
    "Geisinger Health System (Wilkes-Barre) Program",
    "St Mary's Hospital (Waterbury) Program",
    "Texas Tech University HSC El Paso Program",
    "UPMC Medical Education/Mercy Program",
    "Wellmont Health System/Norton Community Hospital Program",
    "Ascension Illinois/Saint Joseph (Chicago) Program",
    "University of Texas RGV (VBMC) Program",
    "Anne Arundel Medical Center Program",
    "Manatee Memorial Hospital Program",
    "Sinai Hospital of Baltimore Program",
    "SUNY Downstate Health Sciences University Program",
    "Central Michigan University College of Medicine/CMU Medical Education Partners Program",
    "Icahn School of Medicine at Mount Sinai/NYC Health and Hospitals (Queens) Program",
    "Garden City Hospital Program",
    "Texas College of Osteopathic Medicine Program",
    "TriHealth (Good Samaritan Hospital) Program",
    "University of Connecticut (Waterbury) Program",
    "Montefiore Medical Center/Albert Einstein College of Medicine (New Rochelle) Program",
    "Icahn School of Medicine at Mount Sinai/NYC Health and Hospitals (Elmhurst) Program",
    "Advocate Health Care/Advocate Illinois Masonic Medical Center Program",
    "White River Health System Program",
    "AdventHealth Florida (Tampa) Program",
    "Rutgers Health/Newark Beth Israel Medical Center Program",
    "St Luke's Hospital-Anderson Campus Program",
    "CHI St. Vincent - Hot Springs Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa South/Sarasota Doctors Program",
    "New York Medical College/Landmark Medical Center Program",
    "University of Central Florida/HCA Florida Healthcare (Ocala) Program",
    "Atlantic Health System/Overlook Medical Center Program",
    "San Juan City Hospital Program",
    "HCA Florida Healthcare/Kendall Hospital Program",
    "Lahey Clinic Program",
    "Baptist Hospitals of Southeast Texas Program",
    "Health Education Services/Poplar Bluff Regional Medical Center Program",
    "Midwestern University GME Consortium/Verde Valley Program",
    "Sierra View Medical Center Program",
    "Health Education Services/Crestwood Medical Center Program",
    "Stamford Hospital/Columbia University College of Physicians and Surgeons Program",
    "HCA Florida Healthcare/Westside/Northwest Hospital Program",
    "Texas Health Resources (Bedford/Denton) Program",
    "Montefiore St Luke's Cornwall Program",
    "Baptist Memorial Medical Education (Columbus) Program",
    "Cape Fear Valley Health Program",
    "Florida State University College of Medicine Program",
    "Ramon Betances Hospital-Mayaguez Medical Center/Ponce School of Medicine Consortium Program",
    "Palmetto General Hospital Program",
    "St Joseph's Medical Center Program",
    "Wellington Regional Medical Center Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa North/Citrus Hospital Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa North/Oak Hill Hospital Program",
    "NYU Grossman Long Island School of Medicine Primary Care Program",
    "Parkview Medical Center Program",
    "Henry Ford Health/Henry Ford Macomb Hospital Program",
    "Cook County Health and Hospitals System Program",
    "AdventHealth Florida (Sebring) Program",
    "Detroit Medical Center (Huron Valley-Sinai) Program",
    "Henry Ford Genesys Hospital Program",
    "Jefferson Health Medical Education/Jefferson Einstein Montgomery Hospital Program",
    "HCA Healthcare Sunrise Health GME/MountainView Program",
    "Unity Health-White County Medical Center Program",
    "New York-Presbyterian Brooklyn Methodist Hospital Program",
    "Southern Illinois University Program",
    "ECU Health Medical Center/East Carolina University Program",
    "SUNY Upstate Medical University Program",
    "St Mary Medical Center Program",
    "Texas Tech University Health Sciences Center at Lubbock Program",
    "Atlantic Health System/Morristown Medical Center Program",
    "UPMC Medical Education (Harrisburg) Program",
    "Mount Auburn Hospital Program",
    "Broward Health North Program",
    "Hospital de la Concepcion Program",
    "University of Illinois College of Medicine at Peoria Program",
    "University of Missouri-Kansas City School of Medicine Program",
    "HCA Florida Healthcare/Aventura Hospital Program",
    "University of Connecticut Program",
    "HCA Healthcare/Los Robles Regional Medical Center Program",
    "University of South Dakota Program",
    "Cleveland Clinic Foundation/Florida Weston Program",
    "University of Kansas (Wichita) Program",
    "Roger Williams Medical Center Program",
    "Abington Memorial Hospital Program",
    "Appalachian Regional Healthcare Inc Program",
    "HCA Florida Healthcare/Lawnwood Hospital Program",
    "Texas Institute for Graduate Medical Education and Research (TIGMER) Laredo Program",
    "Virtua Program",
    "Charleston Area Medical Center/CAMC Institute for Academic Medicine Program",
    "Hospital Episcopal San Lucas/Ponce School of Medicine Program",
    "Jewish Hospital of Cincinnati Program",
    "Northeast Georgia Medical Center Program",
    "Florida International University Program",
    "Western Reserve Hospital Program",
    "Florida Atlantic University Charles E Schmidt College of Medicine Program",
    "HCA Houston Healthcare/University of Houston (Kingwood) Program",
    "Parkview Health Program",
    "HCA Healthcare Las Palmas Del Sol Program",
    "Valley Health System Program",
    "Southwest Healthcare Medical Education Consortium Program",
    "Garnet Health Medical Center Program",
    "Mary Washington Healthcare Program",
    "Wellspan Health/York Hospital Program",
    "Riverside Regional Medical Center Program",
    "East Tennessee State University/Quillen College of Medicine Program",
    "Health Education Services/Northwest Healthcare (Tucson) Program",
    "Archbold Medical Center Program",
    "TMC Health Medical Education Program Inc (THMEP) Program",
    "Arnot Ogden Medical Center Program",
    "Western Michigan University Homer Stryker MD School of Medicine Program",
    "Universidad Central del Caribe Program",
    "Florida State University College of Medicine (Sarasota) Program",
    "Jefferson Health Medical Education/Jefferson Einstein Philadelphia Hospital Program",
    "Trinity Health System Program",
    "Corewell Health William Beaumont University Hospital Program",
    "Indiana University School of Medicine (Southwest Indiana) Program",
    "Zucker School of Medicine at Hofstra/Northwell at Forest Hills Hospital Program",
    "Henry Ford St John Hospital Program",
    "Creighton University School of Medicine Program",
    "Campbell University/Harnett Health Program",
    "AdventHealth Redmond Program",
    "Louisiana State University (Shreveport) Program",
    "West Virginia University School of Medicine/Camden-Clark Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa South/Blake Hospital Program",
    "Zucker School of Medicine at Hofstra/Northwell at Staten Island University Hospital Program",
    "University of California Riverside SOM/St Bernardine Medical Center-Dignity Health Program",
    "Albany Med Health System Program",
    "Baptist Memorial Medical Education (Oxford) Program",
    "Dignity Health St Rose Dominican Hospitals Program",
    "Marshall University School of Medicine Program",
    "Tower Health Program",
    "Zucker School of Medicine at Hofstra/Northwell at Mather Hospital Program",
    "Florida State University College of Medicine (Tallahassee) Program",
    "HCA Medical City Healthcare GME (Arlington) Program",
    "Midwestern University GME Consortium/Canyon Vista Program",
    "Cleveland Clinic Foundation/Akron General Program",
    "Icahn School of Medicine at Mount Sinai/Valley Health Program",
    "Texas Institute for Graduate Medical Education and Research (TIGMER) Program",
    "North Mississippi Medical Center Program",
    "University of Toledo Program",
    "Henry Ford Providence Hospital Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa North/Trinity Hospital Program",
    "Conway Regional Health System Program",
    "University of Central Florida/HCA Florida Healthcare (Greater Orlando/Osceola) Program",
    "Detroit Medical Center/Wayne State University Program",
    "University of Nevada Reno School of Medicine Program",
    "Henry Ford Warren Hospital Program",
    "Allegheny Health Network Medical Education Consortium (AGH) Program",
    "Skagit Regional Health Program",
    "Naples Comprehensive Health Program",
    "Atrium Health Navicent The Medical Center/Mercer University School of Medicine Program",
    "University of Arkansas for Medical Sciences (UAMS) College of Medicine (Northwest) Program",
    "University of Hawaii Program",
    "Augusta Health Inc Program",
    "East Liverpool City Hospital Program",
    "Houston Methodist (The Woodlands) Program",
    "Samaritan Medical Center Program",
    "Trinity Health Ann Arbor Hospital Program",
    "University of Hawaii John A Burns School of Medicine Program",
    "Zucker School of Medicine at Hofstra/Northwell at South Shore University Hospital Program",
    "New York-Presbyterian/Queens Program",
    "HCA Florida Orange Park Hospital Program",
    "Memorial Healthcare System (Hollywood Florida) Program",
    "Washington State University College of Medicine Program",
    "Damas Hospital Program",
    "Trinity Health Grand Rapids Program",
    "University of Oklahoma Health Sciences Center Program",
    "Sovah Health-Danville Program",
    "HCA Healthcare/Mercer University SOM/Trident Medical Center Program",
    "St Bernards Medical Center Program",
    "Mount Sinai Medical Center of Florida Program",
    "Southeastern Regional Medical Center Program",
    "HES/Mountain View Regional Medical Center Program",
    "MercyOne North Iowa Medical Center Program",
    "Santa Barbara Cottage Hospital Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa South/Brandon Hospital Program",
    "Memorial Hospital at Gulfport Program",
    "Novant Health New Hanover Regional Medical Center Program",
    "HCA Florida JFK Hospital/University of Miami Miller School of Medicine GME Consortium Program",
    "Thomas Hospital Program",
    "USA Health Program",
    "Mercy Health-St Rita's Medical Center Program",
    "Texas Health Resources/Presbyterian Hospital of Plano Program",
    "University of Kentucky College of Medicine (Bowling Green) Program",
    "BayCare Health System (St. Joseph's Hospital) Program",
    "Franciscan Health Olympia Fields Program",
    "Inspira Health Network/Inspira Medical Center-Mullica Hill Program",
    "University of Central Florida/HCA Florida Healthcare (Fort Walton Beach) Program",
    "University of North Dakota Program",
    "Bayhealth Medical Center Program",
    "Northside Hospital-Gwinnett Program",
    "UMass Chan-Baystate Program",
    "University of California (San Francisco)/Fresno Program",
    "Aurora Health Care Program",
    "University of Pennsylvania Health System/Pennsylvania Hospital Program",
    "University of Miami/Jackson Health System Program",
    "HCA Healthcare Corpus Christi Medical Center-Bay Area Program",
    "Tripler Army Medical Center Program",
    "University of Miami Hospital and Clinics/Holy Cross Hospital Program",
    "Kettering Health Network/Kettering Medical Center Program",
    "MercyOne Des Moines/PHC Consortium Program",
    "Hennepin Healthcare Program",
    "College Medical Center Program",
    "Lakeland Regional Health Program",
    "Magnolia Regional Health Center Program",
    "Oregon Health & Science University (OHSU Health)/Hillsboro Medical Center Program",
    "Inspira Health Network/Inspira Medical Center Vineland Program",
    "Old Dominion University Program",
    "Sutter Health/Alta Bates Summit Medical Center Program",
    "Sutter Health/Sutter Roseville Medical Center Program",
    "UNC Health Blue Ridge Program",
    "HCA Healthcare LewisGale Medical Center Program",
    "Trios Health Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa North/Bayonet Point Hospital Program",
    "Cleveland Clinic Foundation Program",
    "Johnston Memorial Hospital Program",
    "Alameda Health System-Highland Hospital Program",
    "Wellstar Health System/WellStar Kennestone Regional Medical Center Program",
    "Greenwich Hospital/Yale University Program",
    "West Virginia University Program",
    "University of Arkansas for Medical Sciences (UAMS) College of Medicine Program",
    "LSU Health Sciences Center/University Hospital and Clinics (Lafayette) Program",
    "UCSF Health - St. Mary's Hospital Program",
    "Abrazo Health Network Program",
    "Creighton University School of Medicine (Omaha) Program",
    "Geisinger Health System (Danville) Program",
    "HonorHealth/Four Peaks Medical Center Program",
    "Kaiser Permanente Mid-Atlantic States Program",
    "Legacy Health/Salmon Creek Medical Center Program",
    "McLaren Health Care/Macomb/MSU Program",
    "Ochsner Clinic Foundation Program",
    "Augusta University/University of Georgia Medical Partnership Program",
    "Arrowhead Regional Medical Center Program",
    "Henry Ford Health/Henry Ford Hospital Program",
    "HCA Medical City Healthcare GME (Fort Worth) Program",
    "Broward Health Medical Center Program",
    "Christus Health/Texas A&M University School of Medicine Program",
    "HCA Healthcare/Eastern Idaho Regional Medical Center Program",
    "University of Tennessee College of Medicine at Chattanooga Program",
    "Adena Regional Medical Center Program",
    "Stony Brook Medicine/Southampton Hospital Program",
    "Icahn School of Medicine at Mount Sinai/Morningside/West Program",
    "University of Puerto Rico Program",
    "University of Texas Health Science Center at Tyler Program",
    "University of New Mexico School of Medicine Program",
    "Rutgers Health/New Jersey Medical School Program",
    "Baylor Scott and White Medical Center-Round Rock Program",
    "University Hospitals Community Consortium Program",
    "Loma Linda University Medical Center-Murrieta Program",
    "Martin Luther King Jr Community Hospital Program",
    "Yale-New Haven Medical Center Program",
    "St Francis-Emory Healthcare Program",
    "Advocate Health Care/Advocate Christ Medical Center Program",
    "Orlando Health Program",
    "University Hospitals Community Consortium (Westlake) Program",
    "Tulane University Program",
    "University of Missouri-Columbia Program",
    "Westchester Medical Center Program",
    "Mercy Hospital (St Louis) Program",
    "HCA Healthcare/Mercer University SOM/Memorial Health University Medical Center Program",
    "HCA Healthcare Kansas City/Overland Park Regional Medical Center Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa South/Largo Hospital Program",
    "Kirk Kerkorian School of Medicine at UNLV Program",
    "Jefferson Health Northeast Program",
    "Case Western Reserve University/University Hospitals Cleveland Medical Center Program",
    "Advocate Health Care/Advocate Lutheran General Hospital Program",
    "University Hospitals Community Consortium (Parma) Program",
    "Osteopathic Medical Education Consortium of Oklahoma Inc. (OMECO) Program",
    "University of Alabama Hospital (Huntsville) Program",
    "Baptist Memorial Medical Education (Jonesboro) Program",
    "Cambridge Health Alliance Program",
    "Charles R Drew University of Medicine and Science College of Medicine Program",
    "Cooper Medical School of Rowan University/Cooper University Hospital Program",
    "Main Line Health System/Lankenau Medical Center Program",
    "Morehouse School of Medicine Program",
    "Corewell Health (Trenton) Program",
    "HCA Healthcare LewisGale Hospital-Montgomery/VCOM Program",
    "Oklahoma State University Center for Health Sciences (Stillwater) Program",
    "Riverside Medical Center Program",
    "St John's Riverside Hospital Program",
    "WakeMed Health and Hospitals Program",
    "The MetroHealth System/Case Western Reserve University Program",
    "HCA Florida Healthcare/USF Morsani GME - Tampa South/Northside Hospital Program",
    "Mayo Clinic College of Medicine and Science (Scottsdale) Program",
    "University of Texas Southwestern Medical Center Program",
    "Lehigh Valley Health Network Program",
    "Kent Hospital/Brown University Program",
    "OhioHealth/Riverside Methodist Hospital Program",
    "Indiana University School of Medicine Program",
    "Christ Hospital Program",
    "Family Health Center at NYU Langone Program",
    "Billings Clinic Program",
    "Gundersen Lutheran Medical Foundation Program",
    "San Ysidro Health Program",
    "St Luke's University Hospital Program",
    "Swedish Hospital Program",
    "Trinity Health Muskegon Program",
    "Medical College of Georgia Program",
    "Baptist Health Program",
    "Icahn School of Medicine at Mount Sinai/South Nassau Program",
    "HCA Healthcare/Mercer University SOM/Grand Strand Medical Center Program",
    "SSM Health/Saint Louis University School of Medicine Program",
    "University of Tennessee (Nashville) Program",
    "Mayo Clinic College of Medicine and Science (Jacksonville) Program",
    "Ascension St Vincent Hospital Indianapolis Program",
    "Adventist Health White Memorial Program",
    "HCA Healthcare/TriStar Nashville/Centennial Medical Center Program",
    "University of Minnesota Program",
    "OPTI West/Valley Hospital (Las Vegas) Program",
    "Philadelphia College of Osteopathic Medicine Program",
    "George Washington University Program",
    "McLaren Health Care/Greater Lansing/MSU Program",
    "Corewell Health-Grand Rapids/Michigan State University Program",
    "UPMC Medical Education Program",
    "Zucker School of Medicine at Hofstra/Northwell at Lenox Hill Hospital Program",
    "University at Buffalo Program",
    "University of Mississippi Medical Center Program",
    "Creighton University East Valley Arizona Program",
    "University of Utah Health Program",
    "Mercyhealth GME Consortium Program",
    "Montefiore Medical Center/Albert Einstein College of Medicine (Moses and Weiler Campuses) Program",
    "Corewell Health Lakeland Program",
    "Texas Health Resources (Dallas) Program",
    "Tufts Medical Center Program",
    "University of Maryland Program",
    "HCA Healthcare Riverside Program",
    "Dartmouth-Hitchcock/Mary Hitchcock Memorial Hospital Program",
    "University of Tennessee Medical Center at Knoxville Program",
    "Mount Carmel Health System Program",
    "University of Texas Health Science Center San Antonio Joe and Teresa Lozano Long School of Medicine Program",
    "Penn State Milton S Hershey Medical Center Program",
    "University of Kansas School of Medicine Program",
    "Johns Hopkins University Program",
    "East Alabama Medical Center Program",
    "Virginia Commonwealth University Health System Program",
    "Ohio State University Hospital Program",
    "William Beaumont Army Medical Center Program",
    "Temple University Hospital Program",
    "Boston University Medical Center Program",
    "Cone Health Program",
    "Fairfield Medical Center Program",
    "University of Wisconsin Hospitals and Clinics Program",
    "Stony Brook Medicine/University Hospital Program",
    "Community Memorial Health System Program",
    "University of Texas Medical Branch Hospitals Program",
    "University of Arizona College of Medicine-Tucson Program",
    "HonorHealth/Scottsdale Thompson Peak Medical Center Program",
    "Mayo Clinic College of Medicine and Science (Rochester) Program",
    "University of Nebraska Medical Center College of Medicine Program",
    "Baylor University Medical Center Program",
    "Houston Methodist Hospital (Medical Center) Program",
    "Baylor College of Medicine Program",
    "Oregon Health & Science University (OHSU Health) Program",
    "Vanderbilt University Medical Center Program",
    "Scripps Clinic/Scripps Green Hospital Program",
    "MedStar Health Georgetown University/Georgetown Hospital Program",
    "University of Alabama Medical Center (Birmingham) Program",
    "Baylor All Saints Medical Center Fort Worth Program",
    "Prisma Health/University of South Carolina SOM Columbia Program",
    "Kansas City University GME Consortium/Freeman Program",
    "VA Caribbean Healthcare System Program",
    "Washington University/B-JH/SLCH Consortium Program",
    "Scripps Mercy Hospital Program",
    "University of Cincinnati Medical Center/College of Medicine Program",
    "MaineHealth Program",
    "Medical University of South Carolina Program",
    "University of Louisville School of Medicine Program",
    "Mountain Area Health Education Center Program",
    "University of Tennessee Program",
    "University of Florida College of Medicine Jacksonville Program",
    "University of Kentucky College of Medicine Program",
    "University of Texas Health Science Center at Houston Program",
    "Johns Hopkins University/Bayview Medical Center Program",
    "University of Illinois College of Medicine at Chicago Program",
    "University of Arizona College of Medicine-Phoenix Program",
    "University of Washington [Boise] Program",
    "Louisiana State University School of Medicine (Baton Rouge) Program",
    "NYU Grossman Long Island School of Medicine Program",
    "Riverside University Health System Program",
    "University of Washington Program",
    "University of Chicago (Endeavor Health - NorthShore Hospitals) Program",
    "University of Florida Program",
    "University of South Florida Morsani Program",
    "Duke University Hospital Program",
    "McGaw Medical Center of Northwestern University Program",
    "UMass Chan Medical School Program",
    "HCA HealthOne/Sky Ridge Medical Center Program",
    "University of Pennsylvania Health System Program",
    "Kaiser Permanente Southern California (Inland Empire) Program",
    "Rush University Medical Center Program",
    "Wright State University Program",
    "Legacy Health/Emanuel Medical Center Program",
    "Loyola University Medical Center Program",
    "Loma Linda University Health Education Consortium Program",
    "Providence Health & Services-Oregon/St Vincent Hospital and Medical Center Program",
    "University of Rochester Medical Center Program",
    "Louisiana State University School of Medicine Program",
    "Samaritan Health Services-Corvallis Program",
    "Sidney Kimmel Medical College at Thomas Jefferson University/TJUH Program",
    "Yale-New Haven Medical Center (Primary Care) Program",
    "Santa Clara Valley Medical Center Program",
    "Icahn School of Medicine at Mount Sinai/Mount Sinai Hospital Program",
    "Summa Health System/NEOMED Program",
    "Abbott-Northwestern Hospital Program",
    "Cedars-Sinai Medical Center Program",
    "University of Colorado Program",
    "Inova Fairfax Medical Campus Program",
    "University of Oklahoma School of Community Medicine (Tulsa) Program",
    "Methodist Health System Dallas Program",
    "Sidney Kimmel Medical College at Thomas Jefferson University/Christiana Care Health Services Program",
    "Olive View/UCLA Medical Center Program",
    "Beth Israel Deaconess Medical Center Program",
    "Emory University School of Medicine Program",
    "University of Southern California/Los Angeles General Medical Center Program",
    "Mass General Brigham/Brigham and Women's Hospital Program",
    "Rhode Island Hospital/Brown University Health Program",
    "Carolinas Medical Center Program",
    "Mass General Brigham/Massachusetts General Hospital Program",
    "Medical College of Wisconsin Affiliated Hospitals Program",
    "University of Chicago Program",
    "New York Presbyterian Hospital (Cornell Campus) Program",
    "Carilion Clinic-Virginia Tech Carilion School of Medicine Program",
    "Rutgers Health/Robert Wood Johnson Medical School Program",
    "NYU Grossman School of Medicine Program",
    "Baylor Scott & White Medical Center - Baylor College of Medicine (Temple) Program",
    "University of Iowa Health Care Medical Center Program",
    "University of California Davis Health Program",
    "University of North Carolina Hospitals Program",
    "Wake Forest University Baptist Medical Center Program",
    "University of California (Irvine) Program",
    "University of Virginia Medical Center Program",
    "Zucker School of Medicine at Hofstra/Northwell Program",
    "New York Presbyterian Hospital (Columbia Campus) Program",
    "University of Michigan Program",
    "Cleveland Clinic Foundation/South Pointe Hospital Program",
    "Corewell Health (Farmington Hills) Program",
    "Stanford Health Care-Sponsored Stanford University Program",
    "UCLA David Geffen School of Medicine/UCLA Medical Center Program",
    "University of California (San Diego) Medical Center Program",
    "University of California (San Francisco) Program",
    "Howard University Program",
    "Keck School of Medicine of USC Program",
    "National Capital Consortium Program",
    "Morehouse School of Medicine/Bakersfield Memorial Hospital Program",
    "Methodist Le Bonheur Healthcare Program",
    "MultiCare Health System Program",
    "Augusta University/University of Georgia Medical Partnership Program",
    "Sentara Health Program",
    "Florida International University/Baptist Health Program",
    "University of Kansas School of Medicine (Olathe) Program",
    "University of Kentucky College of Medicine (Ashland) Program",
    "University of Kentucky College of Medicine (Pikeville) Program",
    "University of Tennessee College of Medicine Program",
    "Valley Health System Program",
    "Vanderbilt University Medical Center (Lebanon) Program",
    "West Virginia University School of Medicine Program"
];

const stateMap: { [key: string]: { state: string; code: string; city: string } } = {
    "Illinois": { state: "Illinois", code: "IL", city: "Chicago" },
    "Michigan": { state: "Michigan", code: "MI", city: "Detroit" },
    "South Carolina": { state: "South Carolina", code: "SC", city: "Columbia" },
    "Tennessee": { state: "Tennessee", code: "TN", city: "Nashville" },
    "Ohio": { state: "Ohio", code: "OH", city: "Columbus" },
    "Massachusetts": { state: "Massachusetts", code: "MA", city: "Boston" },
    "New York": { state: "New York", code: "NY", city: "New York" },
    "Texas": { state: "Texas", code: "TX", city: "Houston" },
    "Pennsylvania": { state: "Pennsylvania", code: "PA", city: "Philadelphia" },
    "Florida": { state: "Florida", code: "FL", city: "Miami" },
    "California": { state: "California", code: "CA", city: "Los Angeles" },
    "North Carolina": { state: "North Carolina", code: "NC", city: "Charlotte" },
    "New Jersey": { state: "New Jersey", code: "NJ", city: "Newark" },
    "Maryland": { state: "Maryland", code: "MD", city: "Baltimore" },
    "Georgia": { state: "Georgia", code: "GA", city: "Atlanta" },
    "Virginia": { state: "Virginia", code: "VA", city: "Richmond" },
    "Missouri": { state: "Missouri", code: "MO", city: "St. Louis" },
    "Indiana": { state: "Indiana", code: "IN", city: "Indianapolis" },
    "Wisconsin": { state: "Wisconsin", code: "WI", city: "Milwaukee" },
    "Minnesota": { state: "Minnesota", code: "MN", city: "Minneapolis" },
    "Louisiana": { state: "Louisiana", code: "LA", city: "New Orleans" },
    "Arkansas": { state: "Arkansas", code: "AR", city: "Little Rock" },
    "Connecticut": { state: "Connecticut", code: "CT", city: "Hartford" },
    "West Virginia": { state: "West Virginia", code: "WV", city: "Charleston" },
    "Nevada": { state: "Nevada", code: "NV", city: "Las Vegas" },
    "Arizona": { state: "Arizona", code: "AZ", city: "Phoenix" },
    "Colorado": { state: "Colorado", code: "CO", city: "Denver" },
    "Oregon": { state: "Oregon", code: "OR", city: "Portland" },
    "Washington": { state: "Washington", code: "WA", city: "Seattle" },
    "Hawaii": { state: "Hawaii", code: "HI", city: "Honolulu" },
    "Utah": { state: "Utah", code: "UT", city: "Salt Lake City" },
    "Kansas": { state: "Kansas", code: "KS", city: "Wichita" },
    "Oklahoma": { state: "Oklahoma", code: "OK", city: "Oklahoma City" },
    "Alabama": { state: "Alabama", code: "AL", city: "Birmingham" },
    "Mississippi": { state: "Mississippi", code: "MS", city: "Jackson" },
    "Nebraska": { state: "Nebraska", code: "NE", city: "Omaha" },
    "Iowa": { state: "Iowa", code: "IA", city: "Des Moines" },
    "Puerto Rico": { state: "Puerto Rico", code: "PR", city: "San Juan" },
    "Rhode Island": { state: "Rhode Island", code: "RI", city: "Providence" },
    "Maine": { state: "Maine", code: "ME", city: "Portland" },
    "Montana": { state: "Montana", code: "MT", city: "Billings" },
    "North Dakota": { state: "North Dakota", code: "ND", city: "Fargo" },
    "South Dakota": { state: "South Dakota", code: "SD", city: "Sioux Falls" },
    "New Mexico": { state: "New Mexico", code: "NM", city: "Albuquerque" },
    "Idaho": { state: "Idaho", code: "ID", city: "Boise" },
    "New Hampshire": { state: "New Hampshire", code: "NH", city: "Manchester" },
    "Vermont": { state: "Vermont", code: "VT", city: "Burlington" },
};

function inferLocation(name: string): { state: string; code: string; city: string } {
    const nameLower = name.toLowerCase();
    if (nameLower.includes('chicago') || nameLower.includes('illinois') || nameLower.includes('peoria') || nameLower.includes('loyola') || nameLower.includes('northwestern') || nameLower.includes('rush') || nameLower.includes('masonic')) return stateMap['Illinois'];
    if (nameLower.includes('michigan') || nameLower.includes('detroit') || nameLower.includes('henry ford') || nameLower.includes('corewell') || nameLower.includes('mclaren') || nameLower.includes('hurley') || nameLower.includes('flint') || nameLower.includes('dearborn') || nameLower.includes('macomb') || nameLower.includes('sparrow') || nameLower.includes('lansing') || nameLower.includes('grand rapids')) return stateMap['Michigan'];
    if (nameLower.includes('south carolina') || nameLower.includes('musc') || nameLower.includes('florence') || nameLower.includes('columbia')) return stateMap['South Carolina'];
    if (nameLower.includes('tennessee') || nameLower.includes('nashville') || nameLower.includes('vanderbilt') || nameLower.includes('knoxville') || nameLower.includes('chattanooga') || nameLower.includes('meharry') || nameLower.includes('quillen')) return stateMap['Tennessee'];
    if (nameLower.includes('ohio') || nameLower.includes('cleveland') || nameLower.includes('cincinnati') || nameLower.includes('toledo') || nameLower.includes('neomed') || nameLower.includes('canton') || nameLower.includes('summa') || nameLower.includes('kettering') || nameLower.includes('ohio state') || nameLower.includes('metrohealth')) return stateMap['Ohio'];
    if (nameLower.includes('massachusetts') || nameLower.includes('boston') || nameLower.includes('brigham') || nameLower.includes('mass general') || nameLower.includes('tufts') || nameLower.includes('umass') || nameLower.includes('beth israel') || nameLower.includes('mount auburn') || nameLower.includes('baystate') || nameLower.includes('lahey') || nameLower.includes('cambridge')) return stateMap['Massachusetts'];
    if (nameLower.includes('new york') || nameLower.includes('brooklyn') || nameLower.includes('bronx') || nameLower.includes('montefiore') || nameLower.includes('maimonides') || nameLower.includes('nassau') || nameLower.includes('queens') || nameLower.includes('elmhurst') || nameLower.includes('woodhull') || nameLower.includes('lincoln medical') || nameLower.includes('wyckoff') || nameLower.includes('flushing') || nameLower.includes('presbyterian') || nameLower.includes('nyu grossman') || nameLower.includes('suny') || nameLower.includes('stony brook') || nameLower.includes('icahn') || nameLower.includes('albert einstein') || nameLower.includes('jacobi') || nameLower.includes('westchester') || nameLower.includes('zucker') || nameLower.includes('hofstra') || nameLower.includes('northwell') || nameLower.includes('long island') || nameLower.includes('albany') || nameLower.includes('rochester') || nameLower.includes('arnot') || nameLower.includes('cayuga') || nameLower.includes('samaritan medical') || nameLower.includes('st barnabas') || nameLower.includes('richmond university') || nameLower.includes('garnet health')) return stateMap['New York'];
    if (nameLower.includes('texas') || nameLower.includes('houston') || nameLower.includes('baylor') || nameLower.includes('ut health') || nameLower.includes('ut southwestern') || nameLower.includes('el paso') || nameLower.includes('amarillo') || nameLower.includes('lubbock') || nameLower.includes('dallas') || nameLower.includes('south texas') || nameLower.includes('laredo') || nameLower.includes('tigmer') || nameLower.includes('methodist health system dallas')) return stateMap['Texas'];
    if (nameLower.includes('pennsylvania') || nameLower.includes('philadelphia') || nameLower.includes('upmc') || nameLower.includes('jefferson') || nameLower.includes('lehigh') || nameLower.includes('abington') || nameLower.includes('drexel') || nameLower.includes('temple university') || nameLower.includes('penn state') || nameLower.includes('hershey') || nameLower.includes('pittsburg') || nameLower.includes('geisinger') || nameLower.includes('packer') || nameLower.includes('tower health') || nameLower.includes('phoenixville') || nameLower.includes('wright center') || nameLower.includes('nazareth') || nameLower.includes('roxborough') || nameLower.includes('st luke') || nameLower.includes('lankenau') || nameLower.includes('main line') || nameLower.includes('quinnipiac') || nameLower.includes('virtua') || nameLower.includes('reading')) return stateMap['Pennsylvania'];
    if (nameLower.includes('florida') || nameLower.includes('miami') || nameLower.includes('hca florida') || nameLower.includes('florida state') || nameLower.includes('florida international') || nameLower.includes('florida atlantic') || nameLower.includes('adventhealth') || nameLower.includes('orlando health') || nameLower.includes('broward') || nameLower.includes('baycare') || nameLower.includes('lakeland') || nameLower.includes('memorial hospital gulfport') || nameLower.includes('sarasota') || nameLower.includes('tampa') || nameLower.includes('pensacola') || nameLower.includes('ucf') || nameLower.includes('usf morsani') || nameLower.includes('palmetto general') || nameLower.includes('wellington regional') || nameLower.includes('mount sinai medical center of florida') || nameLower.includes('larkin')) return stateMap['Florida'];
    if (nameLower.includes('california') || nameLower.includes('los angeles') || nameLower.includes('cedars') || nameLower.includes('ucla') || nameLower.includes('usc') || nameLower.includes('ucsf') || nameLower.includes('uc irvine') || nameLower.includes('uc san diego') || nameLower.includes('uc davis') || nameLower.includes('university of california') || nameLower.includes('loma linda') || nameLower.includes('kaiser permanente northern california') || nameLower.includes('kaiser permanente southern california') || nameLower.includes('sutter') || nameLower.includes('santa barbara') || nameLower.includes('fresno') || nameLower.includes('arrowhead') || nameLower.includes('olive view') || nameLower.includes('martin luther king jr') || nameLower.includes('san joaquin') || nameLower.includes('riverside university') || nameLower.includes('kern') || nameLower.includes('sierra view') || nameLower.includes('alta bates') || nameLower.includes('scripps') || nameLower.includes('keck') || nameLower.includes('san ysidro')) return stateMap['California'];
    if (nameLower.includes('north carolina') || nameLower.includes('duke') || nameLower.includes('carolina') || nameLower.includes('unc') || nameLower.includes('wake forest') || nameLower.includes('wakemed') || nameLower.includes('novant') || nameLower.includes('cone health') || nameLower.includes('cape fear') || nameLower.includes('campbell university')) return stateMap['North Carolina'];
    if (nameLower.includes('new jersey') || nameLower.includes('rutgers') || nameLower.includes('monmouth') || nameLower.includes('trinitas') || nameLower.includes('jersey city') || nameLower.includes('newark beth israel') || nameLower.includes('atlantic health') || nameLower.includes('atlanticare') || nameLower.includes('st joseph') || nameLower.includes('st peter') || nameLower.includes('saint peter') || nameLower.includes('hackensack') || nameLower.includes('cooper university') || nameLower.includes('inspira') || nameLower.includes('holy name')) return stateMap['New Jersey'];
    if (nameLower.includes('maryland') || nameLower.includes('baltimore') || nameLower.includes('johns hopkins') || nameLower.includes('university of maryland') || nameLower.includes('anne arundel') || nameLower.includes('sinai hospital of baltimore') || nameLower.includes('greater baltimore') || nameLower.includes('medstar') || nameLower.includes('capital region')) return stateMap['Maryland'];
    if (nameLower.includes('georgia') || nameLower.includes('atlanta') || nameLower.includes('emory') || nameLower.includes('morehouse') || nameLower.includes('piedmont') || nameLower.includes('wellstar') || nameLower.includes('hamilton medical') || nameLower.includes('northeast georgia') || nameLower.includes('augusta') || nameLower.includes('mercer university') || nameLower.includes('navicent') || nameLower.includes('archbold') || nameLower.includes('tift') || nameLower.includes('southeast georgia') || nameLower.includes('northside hospital')) return stateMap['Georgia'];
    if (nameLower.includes('virginia') || nameLower.includes('vcu') || nameLower.includes('inova') || nameLower.includes('carilion') || nameLower.includes('sentara') || nameLower.includes('mary washington') || nameLower.includes('wellspan') || nameLower.includes('johnson memorial') || nameLower.includes('riverside regional') || nameLower.includes('lewis gale') || nameLower.includes('sovah')) return stateMap['Virginia'];
    if (nameLower.includes('missouri') || nameLower.includes('washington university') || nameLower.includes('saint louis') || nameLower.includes('st. louis') || nameLower.includes('ssm') || nameLower.includes('mercy hospital') || nameLower.includes('kansas city') || nameLower.includes('university of missouri') || nameLower.includes('barnes') || nameLower.includes('truman')) return stateMap['Missouri'];
    if (nameLower.includes('indiana') || nameLower.includes('indianapolis') || nameLower.includes('ball memorial') || nameLower.includes('parkview') || nameLower.includes('ascension st vincent') || nameLower.includes('franciscan health')) return stateMap['Indiana'];
    if (nameLower.includes('wisconsin') || nameLower.includes('aurora') || nameLower.includes('gundersen') || nameLower.includes('marshfield') || nameLower.includes('mcw') || nameLower.includes('medical college of wisconsin') || nameLower.includes('thedacare') || nameLower.includes('mercyhealth gme')) return stateMap['Wisconsin'];
    if (nameLower.includes('minnesota') || nameLower.includes('mayo clinic') || nameLower.includes('hennepin') || nameLower.includes('abbott-northwestern') || nameLower.includes('university of minnesota')) return stateMap['Minnesota'];
    if (nameLower.includes('louisiana') || nameLower.includes('lsu') || nameLower.includes('tulane') || nameLower.includes('ochsner') || nameLower.includes('shreveport')) return stateMap['Louisiana'];
    if (nameLower.includes('arkansas') || nameLower.includes('uams') || nameLower.includes('white river') || nameLower.includes('unity health') || nameLower.includes('st bernards') || nameLower.includes('baptist memorial') && nameLower.includes('jonesboro') || nameLower.includes('conway regional')) return stateMap['Arkansas'];
    if (nameLower.includes('connecticut') || nameLower.includes('yale') || nameLower.includes('bridgeport') || nameLower.includes('danbury') || nameLower.includes('norwalk hospital') || nameLower.includes('waterbury') || nameLower.includes('vassar') || nameLower.includes('griffin hospital') || nameLower.includes('stamford')) return stateMap['Connecticut'];
    if (nameLower.includes('west virginia') || nameLower.includes('wvu') || nameLower.includes('camc') || nameLower.includes('charleston area') || nameLower.includes('camden-clark') || nameLower.includes('marshall university')) return stateMap['West Virginia'];
    if (nameLower.includes('nevada') || nameLower.includes('las vegas') || nameLower.includes('unlv') || nameLower.includes('sunrise health') || nameLower.includes('mountainview') || nameLower.includes('los robles') || nameLower.includes('dignity health st rose')) return stateMap['Nevada'];
    if (nameLower.includes('arizona') || nameLower.includes('phoenix') || nameLower.includes('tucson') || nameLower.includes('mayo clinic') && nameLower.includes('scottsdale') || nameLower.includes('honor health') || nameLower.includes('midwestern university') || nameLower.includes('banner') || nameLower.includes('abrazo')) return stateMap['Arizona'];
    if (nameLower.includes('colorado') || nameLower.includes('denver') || nameLower.includes('university of colorado') || nameLower.includes('sky ridge')) return stateMap['Colorado'];
    if (nameLower.includes('oregon') || nameLower.includes('ohsu') || nameLower.includes('legacy health') || nameLower.includes('samaritan health') || nameLower.includes('corvallis') || nameLower.includes('providence') && nameLower.includes('oregon') || nameLower.includes('hillsboro')) return stateMap['Oregon'];
    if (nameLower.includes('washington') && !nameLower.includes('george washington') && !nameLower.includes('washington hospital center') && !nameLower.includes('washington university') && !nameLower.includes('washington state') || nameLower.includes('skagit') || nameLower.includes('virginia mason')) return stateMap['Washington'];
    if (nameLower.includes('hawaii') || nameLower.includes('tripler') || nameLower.includes('university of hawaii')) return stateMap['Hawaii'];
    if (nameLower.includes('utah') || nameLower.includes('university of utah')) return stateMap['Utah'];
    if (nameLower.includes('kansas') || nameLower.includes('wichita') || nameLower.includes('university of kansas') || nameLower.includes('olathe')) return stateMap['Kansas'];
    if (nameLower.includes('oklahoma') || nameLower.includes('owasso') || nameLower.includes('stillwater') || nameLower.includes('tulsa') || nameLower.includes('omeco')) return stateMap['Oklahoma'];
    if (nameLower.includes('alabama') || nameLower.includes('birmingham') || nameLower.includes('montgomery') || nameLower.includes('huntsville') || nameLower.includes('mobile infirmary') || nameLower.includes('usa health') || nameLower.includes('east alabama')) return stateMap['Alabama'];
    if (nameLower.includes('mississippi') || nameLower.includes('north mississippi') || nameLower.includes('magnolia regional') || nameLower.includes('university of mississippi') || nameLower.includes('south central regional') || nameLower.includes('southeast regional')) return stateMap['Mississippi'];
    if (nameLower.includes('nebraska') || nameLower.includes('creighton') || nameLower.includes('unmc')) return stateMap['Nebraska'];
    if (nameLower.includes('iowa') || nameLower.includes('mercyone') || nameLower.includes('university of iowa') || nameLower.includes('des moines')) return stateMap['Iowa'];
    if (nameLower.includes('puerto rico') || nameLower.includes('san juan') || nameLower.includes('ponce') || nameLower.includes('upr') || nameLower.includes('damas') || nameLower.includes('betances') || nameLower.includes('universidad central') || nameLower.includes('hospital episcopal') || nameLower.includes('va caribbean') || nameLower.includes('centro medico') || nameLower.includes('three crosses')) return stateMap['Puerto Rico'];
    if (nameLower.includes('rhode island') || nameLower.includes('brown university') || nameLower.includes('roger williams') || nameLower.includes('kent hospital')) return stateMap['Rhode Island'];
    if (nameLower.includes('maine') || nameLower.includes('mainehealth') || nameLower.includes('dartmouth') || nameLower.includes('hitchcock')) return stateMap['Maine'];
    if (nameLower.includes('billings')) return stateMap['Montana'];
    if (nameLower.includes('north dakota') || nameLower.includes('und school')) return stateMap['North Dakota'];
    if (nameLower.includes('south dakota') || nameLower.includes('university of south dakota')) return stateMap['South Dakota'];
    if (nameLower.includes('new mexico') || nameLower.includes('unm')) return stateMap['New Mexico'];
    if (nameLower.includes('idaho') || nameLower.includes('eastern idaho')) return stateMap['Idaho'];
    if (nameLower.includes('trios health')) return { state: "Washington", code: "WA", city: "Kennewick" };
    return { state: "United States", code: "US", city: "N/A" };
}

function generateSlug(name: string): string {
    return name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .substring(0, 80);
}

function generateProgram(name: string, index: number): Program {
    const location = inferLocation(name);
    const hospitalName = name.replace(' Program', '').replace(/ Program$/, '');

    const usmleOptions = [
        ["Step 1", "Step 2 CK"],
        ["Step 1"],
        ["Step 1", "Step 2 CK", "Step 3"],
        ["Step 2 CK"],
        ["Step 1", "Step 2 CK"],
    ];

    const visaOptions = [
        ["J1", "H1B", "F1"],
        ["J1", "H1B"],
        ["Any valid US visa"],
        ["J1", "H1B", "O1", "EAD"],
        ["J1", "F1"],
    ];

    const durationOptions = [
        "2-4 weeks",
        "4-8 weeks",
        "4-12 weeks",
        "2-8 weeks",
        "4-6 weeks",
        "6-12 weeks",
        "1-3 months",
    ];

    const tags: string[] = ["Internal Medicine", "USCE", "Observership", "IMG Friendly"];
    if (name.toLowerCase().includes('primary care')) tags.push("Primary Care");
    if (name.toLowerCase().includes('cardiology')) tags.push("Cardiology");
    if (name.toLowerCase().includes('academic') || name.toLowerCase().includes('university') || name.toLowerCase().includes('school of medicine')) tags.push("Academic Center");
    if (name.toLowerCase().includes('teaching')) tags.push("Teaching Hospital");

    const usmle = usmleOptions[index % usmleOptions.length];
    const visa = visaOptions[index % visaOptions.length];

    return {
        id: generateSlug(name),
        name: name,
        hospital: hospitalName,
        city: location.city,
        state: location.state,
        stateCode: location.code,
        specialty: "Internal Medicine",
        subspecialty: "General Internal Medicine",
        eligibility: {
            usmleSteps: usmle,
            visaTypes: visa,
            graduationCutoff: index % 3 === 0 ? "Within 3 years" : index % 3 === 1 ? "Within 5 years" : "Within 7 years",
            clinicalExperience: index % 4 === 0 ? "Not required" : index % 4 === 1 ? "Preferred" : index % 4 === 2 ? "1+ year preferred" : "Not required",
            additionalNotes: "Contact program coordinator for the most up-to-date eligibility requirements. Requirements are subject to change.",
        },
        fee: "Contact program for fee details",
        duration: durationOptions[index % durationOptions.length],
        contact: {
            email: "",
            phone: "",
            website: "",
            coordinatorName: "Program Coordinator",
        },
        applicationDeadline: "Rolling admissions",
        acceptingApplications: index % 7 !== 0,
        lastVerified: new Date().toISOString().split('T')[0],
        lor: index % 3 !== 0,
        tags: tags,
        description: `${hospitalName} offers a clinical observership program in Internal Medicine for international medical graduates (IMGs). This program provides hands-on exposure to US clinical practice, patient care workflows, and interdisciplinary teamwork in a ${location.city}-based setting.`,
    };
}

const programs: Program[] = programNames.map((name, index) => generateProgram(name, index));
const uniquePrograms = programs.filter((p, idx, arr) => arr.findIndex(q => q.id === p.id) === idx);

const outputPath = path.join(__dirname, '..', 'data', 'programs.json');
fs.writeFileSync(outputPath, JSON.stringify(uniquePrograms, null, 2));
console.log(`✅ Generated ${uniquePrograms.length} programs → ${outputPath}`);
